# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85d2e1157588fdaea5cb5e69c8c7a1309b862389257a04ccc9cb606757f9631d54b5cd04df61dd48aa2cb09a3950d1e05dfa8cda6a4b6693f4b548341aaf630

test:
  secret_key_base: dfaad78194344b52b58900123810df8308d26081e3f719785b8d87a647fbf195e35e99fc535ac0930651f50fd7517f00ae45a08effe122208fe7efdada4edf8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
